sudo: false
language: python
cache: pip
python:
- "3.4"
- "3.3"
install:
  - pip install pytest flake8 setuptools_scm d2to1
  - pip install -e .
script:
  - py.test testing
  - flake8 testing src setup.py
