sudo: false
language: python
cache:
- directories:
  - $HOME/.pip/cache
  - $HOME/.cache/pip
  - .tox
env:
- TOXEXTRA=flakes
- TOXEXTRA=test
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
install:
- pip install -U pip tox virtualenv setuptools setuptools_scm
script:
- tox -e py-$TOXEXTRA
