sudo: false
language: python
cache:
- directories:
  - $HOME/.pip/cache
  - $HOME/.cache/pip
env:
- TOXEXTRA=flake8
- TOXEXTRA=test
python:
- "3.4"
- "3.5"
install:
- pip install -U pip tox virtualenv setuptools setuptools_scm
script:
- tox -e py-$TOXEXTRA
